[package]
name = "graphics_math"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "graphics_math"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

